**Question 1:** Compare and contrast NLTK and spaCy in terms of features, ease of use,
and performance.

1. Comparison of NLTK and spaCy ( Overview )

* NLTK (Natural Language Toolkit)

  * A traditional, academic-focused NLP library.

  * Designed for teaching, research, and experimentation.

* spaCy

  * An industrial-strength NLP library.

  * Designed for speed, production use, and real-world applications.

2. Feature Comparison

| Feature | NLTK | spaCy |
|---|---|---|
| Design Purpose | Educational, research | Industrial, production |
| Tokenization | Good, flexible | Very fast and accurate |
| POS Tagging | Traditional ML models | State-of-the-art neural models |
| NER (Named Entity Recognition) | Weak, basic | Very strong, high accuracy |
| Dependency Parsing | Basic | Excellent, optimized parser |
| Word Vectors | Must integrate separately | Built-in support |
| Corpora | Comes with many datasets | Minimal built-in corpora |

3. Ease of Use
NLTK

  * Easy for beginners.

  * Lots of tutorials, corpora, and educational resources.

  * But requires more manual coding for advanced tasks.

spaCy

  * Simple API and modern architecture.

  * Many tasks work “out of the box”.

  * But fewer built-in corpora for learning.

4. Performance
NLTK

  * Slower because many algorithms are older and not optimized.

  * Best suited for smaller experiments, not high-speed production.

spaCy

  * Much faster, written in optimized Cython.

  * Uses neural models designed for production.

  * Handles large datasets efficiently.

**Question 2:** What is TextBlob and how does it simplify common NLP tasks like
sentiment analysis and translation?

**What is TextBlob?**

TextBlob is a simple and user-friendly Python library built on top of NLTK and Pattern, designed to make common NLP tasks easier for beginners and rapid application development.

It provides a clean, high-level API for processing textual data without requiring deep knowledge of NLP algorithms.

**How TextBlob Simplifies NLP Tasks**
1. Sentiment Analysis

  * TextBlob provides a built-in sentiment analyzer.

  * It returns polarity (–1 to +1) and subjectivity (0 to 1) with just one line of code.

  * No training, preprocessing, or manual model handling is required.

  Example:

In [ ]:
from textblob import TextBlob

text = TextBlob("I love this app!")
print(text.sentiment)



Sentiment(polarity=0.625, subjectivity=0.6)


2. Translation

  * TextBlob uses an internal API (Pattern/Google Translate backend) to translate text.

  * Again, only one line of code is needed.

3. Other Simplified NLP Tasks

TextBlob also makes these easy:

  * Tokenization (text.words, text.sentences)

  * POS tagging (text.tags)

  * Noun phrase extraction (text.noun_phrases)

  * Spell correction (text.correct())

**Question 3:** Explain the role of Standford NLP in academic and industry NLP Projects.

Role of Stanford NLP in Academic and Industry NLP Projects

Stanford NLP (Stanford CoreNLP) is a powerful suite of natural language processing tools developed by Stanford University. It provides state-of-the-art algorithms for various language analysis tasks.

1. Role in Academic Research

a) Benchmark for NLP tasks

Stanford NLP provides high-quality models for POS tagging, NER, parsing, and sentiment analysis, which serve as benchmarks for research studies.

b) Linguistically accurate models

The tools are developed with strong linguistic theories, making them highly suitable for linguistic research, corpus studies, and computational linguistics projects.

c) Multilingual support for cross-linguistic research

It supports many languages, helping researchers work on multilingual NLP experiments.

d) Open-source and widely cited

Stanford NLP tools are open-source and extensively referenced, making them a reliable choice for academic publications.

2. Role in Industry Applications

a) Production-grade NLP pipeline

Companies use CoreNLP for tasks like:

* Named Entity Recognition

* Sentiment Analysis

* Dependency Parsing

* Coreference Resolution

It provides stable, mature, and accurate components.

b) Good for rule-based + statistical hybrid systems

Industry workflows often require combining linguistic rules with machine learning, which CoreNLP supports well.

c) Integration with enterprise systems

CoreNLP can be deployed as a server, consumed through REST APIs, and integrated into:

* Customer service chatbots

* Search engines

* Document analysis systems

* Information extraction pipelines

d) Strong performance for structured text extraction

Industries like finance, healthcare, and legal use CoreNLP to extract information from large volumes of unstructured text.

**Question 4:** Describe the architecture and functioning of a Recurrent Natural Network (RNN).

Recurrent Neural Network (RNN): Architecture and Functioning

A Recurrent Neural Network (RNN) is a type of neural network designed to process sequential data such as text, speech, or time-series. Unlike traditional neural networks, RNNs have a memory of previous inputs.

1. Architecture of an RNN

a) Input Layer

* Takes sequential data as input.

* Example: words in a sentence → one word at each time step t.

b) Hidden Layer (core of RNN)

* Contains recurrent connections, meaning the output of the hidden layer at time t is fed back as input at time t+1.

* This creates a memory of previous steps.

c) Output Layer

* Produces output at each time step.

* Depending on the task:

  * Classification: one output at final step

  * Sequence prediction: one output per time step

  2. Key Characteristic: Recurrence

The RNN updates its hidden state using:

ℎ
𝑡=
𝑓
(
𝑊
𝑥
𝑡
+
𝑈
ℎ
𝑡
−
1
+
𝑏
)

Where:
h
t
	​

 = hidden state at time t
x
t
	​

 = input at time t
1
h
t−1
	​

 = previous hidden state

W,U = weight matrices


f = activation function (tanh or ReLU)

This enables RNNs to store past information and learn temporal dependencies.

Functioning of an RNN (Step-by-Step)

Step 1:

Take the first input (e.g., first word) → compute hidden state
ℎ
1
h
1
	​


Step 2:

Next input + previous hidden state → compute
ℎ
2
h
2
	​


Step 3:

Continue this process across the entire sequence.

Step 4:

Generate output using the final hidden state or each hidden state (depending on the task).

This flow allows RNNs to understand context, such as:

  * Meaning of a sentence

  * Time dependencies in stock prices

  * Speech signals

4. Strengths of RNNs

* Good for sequential and temporal data

* Maintains memory of previous inputs

* Useful for NLP tasks like:

  * Language modeling

  * Text generation

  * Machine translation

5. Limitations of RNNs

* Suffer from vanishing and exploding gradient problems

* Struggle to learn long-term dependencies

* Replaced mostly by LSTMs, GRUs, and Transformers

**Question 5:** What is the key difference between LSTM and GRU networks in NLP
applications?

**Key Difference Between LSTM and GRU Networks**

Both LSTMs (Long Short-Term Memory) and GRUs (Gated Recurrent Units) are advanced RNN architectures designed to solve the vanishing gradient problem and handle long-term dependencies.
However, they differ in structure and complexity.

1. Architectural Difference

LSTM

* nHas three gates:
  * Input Gate
  * Forget Gate
  * Output Gate

* Maintains two states:
  * Hidden state (h)
  * Cell state (c)

GRU

* Has two gates:
  * Update Gate
  * Reset Gate

* Maintains only one state:
  *Hidden state (h)

GRU is a simplified version of LSTM with fewer parameters.

2. Performance & Usage Differences

LSTM

  * More powerful and expressive due to two states.

  * Better for very complex sequences or longer dependencies.

  * Slightly slower due to more gates.

GRU

  * Faster to train because it has fewer parameters.

  * Performs similarly or sometimes better on small datasets.

  * Usually preferred when speed and efficiency matter.

**Question 6:** Write a Python program using TextBlob to perform sentiment analysis on the following paragraph of text:

“I had a great experience using the new mobile banking app. The interface is intuitive, and customer support was quick to resolve my issue. However, the app did crash once during a transaction, which was frustrating"

Your program should print out the polarity and subjectivity scores.


In [ ]:
from textblob import TextBlob

text = """
I had a great experience using the new mobile banking app.
The interface is intuitive, and customer support was quick to resolve my issue.
However, the app did crash once during a transaction, which was frustrating.
"""

# Create TextBlob object
blob = TextBlob(text)

# Get polarity and subjectivity
polarity = blob.sentiment.polarity
subjectivity = blob.sentiment.subjectivity

# Print results
print("Polarity:", polarity)
print("Subjectivity:", subjectivity)


Polarity: 0.21742424242424244
Subjectivity: 0.6511363636363636


**Question 7:** Given the sample paragraph below, perform string tokenization and frequency distribution using Python and NLTK:

“Natural Language Processing (NLP) is a fascinating field that combines linguistics, computer science, and artificial intelligence. It enables machines to understand, interpret, and generate human language. Applications of NLP include chatbots, sentiment analysis, and machine translation. As technology advances, the role of NLP in modern solutions is becoming increasingly critical.”


In [ ]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.probability import FreqDist

# Download required resources (run once)
nltk.download('punkt_tab') # Changed from 'punkt' to 'punkt_tab' as per error message

text = """
Natural Language Processing (NLP) is a fascinating field that combines linguistics,
computer science, and artificial intelligence. It enables machines to understand,
interpret, and generate human language. Applications of NLP include chatbots,
sentiment analysis, and machine translation. As technology advances, the role of NLP
in modern solutions is becoming increasingly critical.
"""

# 1. Tokenization
tokens = word_tokenize(text)
print("Tokens:")
print(tokens)

# 2. Frequency Distribution
freq_dist = FreqDist(tokens)

print("\nFrequency Distribution:")
for word, freq in freq_dist.most_common(10):
    print(f"{word} : {freq}")

Tokens:
['Natural', 'Language', 'Processing', '(', 'NLP', ')', 'is', 'a', 'fascinating', 'field', 'that', 'combines', 'linguistics', ',', 'computer', 'science', ',', 'and', 'artificial', 'intelligence', '.', 'It', 'enables', 'machines', 'to', 'understand', ',', 'interpret', ',', 'and', 'generate', 'human', 'language', '.', 'Applications', 'of', 'NLP', 'include', 'chatbots', ',', 'sentiment', 'analysis', ',', 'and', 'machine', 'translation', '.', 'As', 'technology', 'advances', ',', 'the', 'role', 'of', 'NLP', 'in', 'modern', 'solutions', 'is', 'becoming', 'increasingly', 'critical', '.']

Frequency Distribution:
, : 7
. : 4
NLP : 3
and : 3
is : 2
of : 2
Natural : 1
Language : 1
Processing : 1
( : 1


[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


**Question 8:** Implement a basic LSTM model in Keras for a text classification task using
the following dummy dataset. Your model should classify sentences as either positive
(1) or negative (0).
# Dataset

texts = [
  
  “I love this project”, #Positive

  “This is an amazing experience”, #Positive

  “I hate waiting in line”, #Negative

  “This is the worst service”, #Negative

  “Absolutely fantastic!” #Positive

]

labels = [1, 1, 0, 0, 1]

Preprocess the text, tokenize it, pad sequences, and build an LSTM model to train on this data. You may use Keras with TensorFlow backend.


In [ ]:
# Install TensorFlow if needed:
# !pip install tensorflow

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
import numpy as np

# -----------------------------------------------------
# 1. Dummy Dataset
# -----------------------------------------------------
texts = [
    "I love this project",              # Positive
    "This is an amazing experience",    # Positive
    "I hate waiting in line",           # Negative
    "This is the worst service",        # Negative
    "Absolutely fantastic!"             # Positive
]

labels = [1, 1, 0, 0, 1]  # 1 = Positive, 0 = Negative

# -----------------------------------------------------
# 2. Tokenization
# -----------------------------------------------------
tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)

sequences = tokenizer.texts_to_sequences(texts)
word_index = tokenizer.word_index

print("Word Index:", word_index)
print("Sequences:", sequences)

# -----------------------------------------------------
# 3. Padding Sequences
# -----------------------------------------------------
max_len = max(len(seq) for seq in sequences)
padded_sequences = pad_sequences(sequences, maxlen=max_len, padding='post')

print("\nPadded Sequences:")
print(padded_sequences)

# Convert labels to numpy array
labels = np.array(labels)

# -----------------------------------------------------
# 4. Build LSTM Model
# -----------------------------------------------------
model = Sequential()
model.add(Embedding(input_dim=len(word_index) + 1, output_dim=32, input_length=max_len))
model.add(LSTM(64))
model.add(Dense(1, activation='sigmoid'))

model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

# -----------------------------------------------------
# 5. Train the Model
# -----------------------------------------------------
history = model.fit(padded_sequences, labels, epochs=10, verbose=1)

# -----------------------------------------------------
# 6. Testing the model with a sample input
# -----------------------------------------------------
test_text = ["I absolutely love this service"]
test_seq = tokenizer.texts_to_sequences(test_text)
test_pad = pad_sequences(test_seq, maxlen=max_len, padding='post')

prediction = model.predict(test_pad)
print("\nPrediction Score:", prediction)
print("Sentiment:", "Positive" if prediction > 0.5 else "Negative")


Word Index: {'this': 1, 'i': 2, 'is': 3, 'love': 4, 'project': 5, 'an': 6, 'amazing': 7, 'experience': 8, 'hate': 9, 'waiting': 10, 'in': 11, 'line': 12, 'the': 13, 'worst': 14, 'service': 15, 'absolutely': 16, 'fantastic': 17}
Sequences: [[2, 4, 1, 5], [1, 3, 6, 7, 8], [2, 9, 10, 11, 12], [1, 3, 13, 14, 15], [16, 17]]

Padded Sequences:
[[ 2  4  1  5  0]
 [ 1  3  6  7  8]
 [ 2  9 10 11 12]
 [ 1  3 13 14 15]
 [16 17  0  0  0]]
Epoch 1/10


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.0000e+00 - loss: 0.6982
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.2000 - loss: 0.6955
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.6000 - loss: 0.6928
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.6000 - loss: 0.6901
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6000 - loss: 0.6875
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.6000 - loss: 0.6848
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6000 - loss: 0.6820
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.6000 - loss: 0.6792
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.6000 - loss: 0.6761
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.6000 - loss: 0.6728
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 393ms/step

Prediction Score: [[0.52121705]]
Sentiment: Positive


**Question 9:** Using spaCy, build a simple NLP pipeline that includes tokenization, lemmatization, and entity recognition. Use the following paragraph as your dataset:

“Homi Jehangir Bhaba was an Indian nuclear physicist who played a key role in the development of India’s atomic energy program. He was the founding director of the Tata Institute of Fundamental Research (TIFR) and was instrumental in establishing the Atomic Energy Commission of India.”

Write a Python program that processes this text using spaCy, then prints tokens, their lemmas, and any named entities found.


In [ ]:
# Install spaCy model if needed:
# !python -m spacy download en_core_web_sm

import spacy

# Load spaCy English model
nlp = spacy.load("en_core_web_sm")

text = """
Homi Jehangir Bhaba was an Indian nuclear physicist who played a key role in the
development of India’s atomic energy program. He was the founding director of the Tata
Institute of Fundamental Research (TIFR) and was instrumental in establishing the
Atomic Energy Commission of India.
"""

# Process the text
doc = nlp(text)

# ---------------------------------------------------------
# 1. Tokenization and Lemmatization
# ---------------------------------------------------------
print("Tokens and Lemmas:\n")
for token in doc:
    if not token.is_space:
        print(f"{token.text:20} -->  {token.lemma_}")

# ---------------------------------------------------------
# 2. Named Entity Recognition (NER)
# ---------------------------------------------------------
print("\nNamed Entities Found:\n")
for ent in doc.ents:
    print(f"{ent.text:40} -->  {ent.label_}")


Tokens and Lemmas:

Homi                 -->  Homi
Jehangir             -->  Jehangir
Bhaba                -->  Bhaba
was                  -->  be
an                   -->  an
Indian               -->  indian
nuclear              -->  nuclear
physicist            -->  physicist
who                  -->  who
played               -->  play
a                    -->  a
key                  -->  key
role                 -->  role
in                   -->  in
the                  -->  the
development          -->  development
of                   -->  of
India                -->  India
’s                   -->  ’s
atomic               -->  atomic
energy               -->  energy
program              -->  program
.                    -->  .
He                   -->  he
was                  -->  be
the                  -->  the
founding             -->  found
director             -->  director
of                   -->  of
the                  -->  the
Tata                 -->  Tata
Institute  

**Question 10:** You are working on a chatbot for a mental health platform. Explain how you would leverage LSTM or GRU networks along with libraries like spaCy or Stanford NLP to understand and respond to user input effectively. Detail your architecture, data preprocessing pipeline, and any ethical considerations.


**1. System Architecture Overview**

A mental-health chatbot typically involves three major components:

(1) NLP Understanding Block (spaCy / StanfordNLP)

Used for:

* Tokenization

* Lemmatization

* POS tagging

* Dependency parsing

* Named Entity Recognition (NER)

* Detecting emotion-related keywords (e.g., “anxious,” “alone”)

(2) Deep Learning Module (LSTM or GRU)

Used for:

* Intent classification

* Emotion detection

* Generating context-aware responses

* Predicting user sentiment over time

(3) Response Generation Layer

* Rule-based templates for clinical safety

* Retrieval-based responses from curated mental-health resources

* Escalation to human counselor when needed

**2. Data Preprocessing Pipeline**

To prepare the text for an LSTM/GRU model:

Step 1: Text Cleaning

  * Lowercasing

  * Removing URLs, emojis, special characters

  * Removing stopwords cautiously (e.g., keep “not,” “never” for mental health context)

Step 2: Tokenization (spaCy or StanfordNLP)

  * Break sentences into tokens

  * Identify parts of speech

  * Extract meaningful phrases (“feeling depressed”, “panic attack”)

Step 3: Lemmatization

  * Convert “feeling → feel”, “cried → cry”

  * Helps generalize emotional expressions

Step 4: Sequence Preparation

  * Convert tokens to integers using Tokenizer

  * Pad sequences for uniform shape

Step 5: Labeling

Train on categories such as:

  * Stress

  * Anxiety

  * Depression indicators

  * Seeking motivation

  * Neutral conversation

Step 6: Embedding Layer

Use:

  * GloVe embeddings

  * Word2Vec

  * Or spaCy vectors (300-dim)

These embeddings help the LSTM/GRU understand emotional nuances.

In [ ]:
# Install required libraries
# !pip install spacy tensorflow
# !python -m spacy download en_core_web_sm

import spacy
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

# ---------------------------------------------------------
# 1. Load spaCy NLP model
# ---------------------------------------------------------
nlp = spacy.load("en_core_web_sm")

# ---------------------------------------------------------
# 2. Dummy mental-health dataset (intent classification)
# ---------------------------------------------------------
texts = [
    "I feel very sad and alone",
    "I'm stressed because of exams",
    "I had a good day today",
    "Life feels overwhelming right now",
    "I am happy and grateful",
    "I need some motivation",
    "I am anxious about my future"
]

# Labels (0 = Negative emotions, 1 = Positive/Neutral)
labels = [0, 0, 1, 0, 1, 1, 0]

# ---------------------------------------------------------
# 3. Preprocessing with spaCy (tokenization + lemmatization)
# ---------------------------------------------------------
def spacy_preprocess(text):
    doc = nlp(text)
    return " ".join([token.lemma_.lower() for token in doc if not token.is_stop])

processed_texts = [spacy_preprocess(t) for t in texts]
print("Processed Texts:", processed_texts)

# ---------------------------------------------------------
# 4. Tokenization + Sequence padding
# ---------------------------------------------------------
tokenizer = Tokenizer()
tokenizer.fit_on_texts(processed_texts)

seqs = tokenizer.texts_to_sequences(processed_texts)
max_len = max(len(s) for s in seqs)
padded_seqs = pad_sequences(seqs, maxlen=max_len, padding='post')

labels = np.array(labels)

# ---------------------------------------------------------
# 5. Build LSTM Model
# ---------------------------------------------------------
model = Sequential()
model.add(Embedding(input_dim=len(tokenizer.word_index)+1,
                    output_dim=32,
                    input_length=max_len))
model.add(LSTM(64))
model.add(Dense(1, activation="sigmoid"))

model.compile(loss="binary_crossentropy",
              optimizer="adam",
              metrics=["accuracy"])

# ---------------------------------------------------------
# 6. Train model
# ---------------------------------------------------------
model.fit(padded_seqs, labels, epochs=10, verbose=1)

# ---------------------------------------------------------
# 7. Test chatbot understanding
# ---------------------------------------------------------
def predict_intent(msg):
    processed = spacy_preprocess(msg)
    seq = tokenizer.texts_to_sequences([processed])
    pad = pad_sequences(seq, maxlen=max_len, padding='post')
    pred = model.predict(pad)[0][0]
    return "Positive/Neutral" if pred > 0.5 else "Negative Emotion"

test_message = "I feel hopeless and tired"
print("\nUser:", test_message)
print("Predicted Intent:", predict_intent(test_message))


Processed Texts: ['feel sad', 'stress exam', 'good day today', 'life feel overwhelming right', 'happy grateful', 'need motivation', 'anxious future']
Epoch 1/10


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.4286 - loss: 0.6932
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - accuracy: 0.7143 - loss: 0.6917
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.5714 - loss: 0.6902
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - accuracy: 0.5714 - loss: 0.6886
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5714 - loss: 0.6871
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.5714 - loss: 0.6854
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5714 - loss: 0.6836
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - accuracy: 0.5714 - loss: 0.6817
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5714 - loss: 0.6796
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5714 - loss: 0.6773

User: I feel hopeless and tired
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 261ms/step
Predicted Intent: Negative Emotion
